### ISSUE TITLE
pretrained SSL weights

### ISSUE THREAD

**Issue by jaypatravali** [BestJuly/IIC#1]
Hi could you please provide weights for your SSL method?

Thanks.

**Comment by BestJuly** [comment]
Hi, @jaypatravali. Thank you for your interest.

I have added some information about pretrained weights in this repo. By using this model, you should achieve exactly the same results as that reported in the paper for video retrieval.

**Comment by BestJuly** [comment]
I also attached one pretrained weight for finetuning on UCF101 split 1. I will conduct experiments using other network architectures in the future and once completed, more SSL weights will be added by a link.
