### ISSUE TITLE
Question about pretraining

### ISSUE THREAD

**Issue by PipiZong** [BestJuly/IIC#12]
Thanks for sharing your great work.

Just wondering which model do you select for the downstream task since you save pertaining models every 40 epochs.

Thank you.

**Comment by BestJuly** [comment]
Thank you for your interest. 

For the pretraining part, I am just using the last epoch. 
I have tried using different checkpoints for downstream task, the differences are limited, and there exist a better checkpoint. However, that is tricky and based on the testing performance. Therefore, only the last checkpoint will be used.
