### ISSUE TITLE
方法泛化

### ISSUE THREAD

**Issue by yxlijun** [BestJuly/IIC#3]
该自监督方法对短视频这种特征提取效果怎么样

**Comment by BestJuly** [comment]
Hi, @yxlijun 

不太清楚你对短视频的定义是什么样的。对于视频中常用的数据集而言，UCF101/HMDB51/Kinetics/Something-something/..., 这些数据集里本身就是裁剪好的短视频，通常一个视频十几秒。

对于效果而言，评价标准多种多样。从video retrieval和video recognition上来讲，论文里对于这两点都有实验论证。

在Readme里也有提及，本方法理论上可以泛化到
- 不同的模型；
- 不同的自监督学习(contrastive learning)的方法；
- 视频特征下游的任务 (by fine-tuning).
